### ISSUE TITLE
Tracking: Wanted Blueprints

### ISSUE THREAD

**Issue by adamziel** [WordPress/blueprints#31]
While you can submit any Blueprint to this repository, here's a few ideas that would be particularly helpful and people have requested in the past (e.g. in the [Add 10 initial Blueprints](https://github.com/adamziel/blueprints/issues/1) issue)

## Highly useful Blueprints

- XML import with a good demo content (not test content) [requested by](https://github.com/adamziel/blueprints/issues/1#issuecomment-1998059598) @justintadlock. [This example](https://github.com/ndiego/icon-block/blob/fc7c7f0c2851c7146eb6d87aef86d9b6c106546a/_playground/blueprint.json#L20C3-L26C4) by @ndiego or [this one](https://github.com/adamziel/blueprints/issues/1#issuecomment-2037563134) from @ryanwelcher or [this one](https://github.com/adamziel/blueprints/issues/1#issuecomment-2041185493) from @helgatheviking could be helpful.
- Block Museum as a Blueprint https://block-museum.com/ 

Furthermore, the following ideas seem particularly interesting:

## Showcase great WordPress features

* [ ] https://github.com/WordPress/blueprints/issues/46
* [ ] Block hooks example 
* [ ] Twenty Twenty Four with...
   * [ ] Block template parts
    * [ ] theme.json
    * [ ] theme.json and various block options for color limited 
    * [ ] locked blocks or patterns
    * [ ] both theme provided and custom starter patterns, along with patterns prioritized from the pattern directory
    * [ ] various block options limited (duotone, color, typography tools) and client side filtering for some blocks 
* [ ] Setup for creating a new theme with a [create-block-theme](https://github.com/WordPress/create-block-theme/) plugin

## Create Content

- [ ] Generate content with Fakerpress (plugin demo, content)
- [ ] Convert Markdown to WordPress posts (read file via wp-cli)
- [ ] Migrate all Markdown related docs pages to WordPress

## Maintenance, Optimization, Configuration

- [ ] Start with a fresh WordPress install via [Site Cleanup plugin](https://github.com/janw-me/default-featured-image/blob/main/.wordpress-org/blueprints/blueprint.json)
- [ ] [Speculative Loading](https://make.wordpress.org/core/2024/04/09/speculative-loading-in-wordpress/) for faster site
- [ ] Run Performance Lab on a site

## Testing, Debugging

- [ ] Enforce WordPress Coding Standards (use Plugin Review Check)
- [ ] Theme Check plugin
- [ ] Debugging with the [Debug Bar](https://wordpress.org/plugins/debug-bar/) plugin
- [x] Log in as a user with editor role

## Learn WordPress JavaScript APIs

- Working with the datastore (see the [course](https://developer.wordpress.org/block-editor/how-to-guides/data-basics/) and the [existing Blueprint](https://github.com/WordPress/block-development-examples/tree/trunk/plugins/data-basics-59c8f8))
  - Get data from WordPress in JavaScript (use hooks)
  - useSelect example
  - Working with a custom datastore

Props to @flexseth, @annezazu, @justintadlock, @ryanwelcher, @helgatheviking, and @bph for sharing these!

**Comment by carstingaxion** [comment]
> * Block hooks example

… is included in #48 ;)
