### ISSUE TITLE
Blueprint review checklist

### ISSUE THREAD

**Issue by adamziel** [WordPress/blueprints#42]
Let's co-create a Blueprint review checklist for the future reviewers. Here's the initial draft:

## How to get started?

* Subscribe to all the new PRs and issues in this repository to get notifications about new submissions

## What to review?

* New Pull Requests without any labels
* Pull Requests with a "needs review" label

## How to review?

- [ ] Does the PR fulfill the [contribution guidelines](https://github.com/WordPress/blueprints/blob/trunk/CONTRIBUTING.md#submit-your-blueprint-to-this-repository)?
    - [ ] It has a dedicated directory for the Blueprint
    - [ ] There's only a single Blueprint.json file
    - [ ] No files outside of the WordPress/Blueprints repository (or reasonable wp.org URLs) are referenced
    - [ ] Does the Blueprint come with a clear title and description?
- [ ] Do the automated GitHub checks pass?
- [ ] Does the Blueprint actually work when previewed? Does it load reasonably fast? Are there any errors in the browser devtools?

## What to do next?

If the answer to all these questions is "yes", you can just merge the Pull Request. The gallery will be automatically refreshed by a CI job. You're done!

If the answer to any of these questions is "no":

* Leave feedback for the person submitting the Pull Request.
* Tell them exactly what's wrong and give them tips on how to improve it. Over time we should accumulate a nice "copy&paste" database of those tips to streamline the process.
* If they reply, re-review.
* If they don't reply within 14 days, close the PR.

----

This simple workflow may suffice. If it doesn't, let's explore:

* Automatically adding "awaiting review" and "needs changes" labels when the PR is created and commented on
* A project board with columns representing PRs with those labels
